/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clock.gui;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import javax.swing.JToggleButton;

class NewAlarmDialogTest {
    @Test
    void isDaySelectedTest() {
        NewAlarmDialog classUnderTest = new NewAlarmDialog();
        assertFalse(classUnderTest.isDaySelected());
        classUnderTest.getWeekDays()[3].setSelected(true);
        assertTrue(classUnderTest.isDaySelected());
    }

    @Test
    void isTimeSelectedTest() {
        NewAlarmDialog classUnderTest = new NewAlarmDialog();
        assertFalse(classUnderTest.isTimeSelected());
        classUnderTest.getHoursList().setSelectedIndex(0);
        assertFalse(classUnderTest.isTimeSelected());
        classUnderTest.getMinutesList().setSelectedIndex(0);
        assertFalse(classUnderTest.isTimeSelected());
        classUnderTest.getAmpmMarkerList().setSelectedIndex(0);
        assertTrue(classUnderTest.isTimeSelected());
    }

    @Test
    void getSelectedSettingsTest() {
        NewAlarmDialog classUnderTest = new NewAlarmDialog();
        // [1,1,0,0,0,0,0,0,1,15,0,2,15]
        int[] expectedArray = { 1, 1, 0, 0, 0, 0, 0, 0, 1, 15, 0, 2, 15 };
        classUnderTest.getWeekDays()[0].setSelected(true);
        classUnderTest.getWeekDays()[1].setSelected(true);
        classUnderTest.getHoursList().setSelectedIndex(1);
        classUnderTest.getMinutesList().setSelectedIndex(15);
        classUnderTest.getAmpmMarkerList().setSelectedIndex(0);
        assertArrayEquals(expectedArray, classUnderTest.getSelectedSettings());
    }

    @Test
    void displaySetAlarmSettingsTest() {
        NewAlarmDialog classUnderTest = new NewAlarmDialog();
        int[] alarmSettings = { 1, 1, 0, 0, 0, 0, 0, 0, 1, 15, 0, 2, 15 };

        classUnderTest.displaySetAlarmSettings(alarmSettings);

        boolean[] expectedBoolArray = { true, true, false, false, false, false, false };

        for (int i = 0; i < alarmSettings.length - 6; i++) {
            assertEquals(expectedBoolArray[i], classUnderTest.getWeekDays()[i].isSelected());
        }

        assertTrue(classUnderTest.getHoursList().isSelectedIndex(1));
        assertTrue(classUnderTest.getMinutesList().isSelectedIndex(15));
        assertTrue(classUnderTest.getAmpmMarkerList().isSelectedIndex(0));
    }

    @Test
    void clearNewAlarmDialogSelectionsTest() {
        NewAlarmDialog classUnderTest = new NewAlarmDialog();
        // [1,1,0,0,0,0,0,0,1,15,0,2,15]
        classUnderTest.getWeekDays()[0].setSelected(true);
        classUnderTest.getWeekDays()[1].setSelected(true);
        classUnderTest.getHoursList().setSelectedIndex(1);
        classUnderTest.getMinutesList().setSelectedIndex(15);
        classUnderTest.getAmpmMarkerList().setSelectedIndex(0);
        classUnderTest.clearNewAlarmDialogSelections();

        for (JToggleButton tb : classUnderTest.getWeekDays())
            assertFalse(tb.isSelected());

        assertTrue(classUnderTest.getHoursList().isSelectionEmpty());
        assertTrue(classUnderTest.getMinutesList().isSelectionEmpty());
        assertTrue(classUnderTest.getAmpmMarkerList().isSelectionEmpty());

    }
}
